name: 22-in

on:
  # Isse automatic build band ho jayega aur Manual button enable ho jayega
  workflow_dispatch: 

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Agar aapki files root mein hain to '.' rehne dein
          # Agar kisi folder (e.g. docs) mein hain to folder name likhein
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
